### ISSUE TITLE
Is there away to import custom icons?

### ISSUE THREAD

**Issue by Glowing0v3rlord** [cgytrus/ThreeDashTools#5]
Hi, I was wondering if it would be possible to create my own icons and import them into 3DashTools for use. Can you let me know if that's possible, and maybe add it as a feature if it's not?

**Comment by cgytrus** [comment]
yeah, you can, see [ThreeDashTools.Assets](https://github.com/cgytrus/ThreeDashTools/tree/main/ThreeDashTools.Assets) for an example/template

**Comment by Glowing0v3rlord** [comment]
How do you reply so fast?! Lol

**Comment by cgytrus** [comment]
discord webhook

**Comment by Glowing0v3rlord** [comment]
Where's the template? I don't see it

**Comment by cgytrus** [comment]
use the project as the template
rename the assetbundle to smth different
remove the existing models and make your own (with different names) and use the existing ones as examples
